# Generated by Django 5.1.1 on 2024-09-06 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='object',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='object',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='object',
            name='status',
            field=models.CharField(choices=[('IN_PROCESS', 'In Process'), ('FINISHED', 'Finished')], default='IN_PROCESS', max_length=50),
        ),
        migrations.AddField(
            model_name='object',
            name='title',
            field=models.CharField(default='TITLE', max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='object',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='objects', verbose_name='Фото')),
                ('object_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.object')),
            ],
        ),
    ]
