# Generated by Django 5.1.1 on 2024-09-06 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_object_description_object_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
