# Generated by Django 5.1.1 on 2024-09-06 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_object_options_alter_objectphoto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectphoto',
            name='object_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apis.object'),
        ),
    ]
