# Generated by Django 5.1.1 on 2024-09-06 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_objectphoto_object_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='object',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='object',
            name='status',
            field=models.CharField(choices=[('IN_PROCESS', 'In Process'), ('FINISHED', 'Finished')], default='IN_PROCESS', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='objectphoto',
            name='object_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apis.object', verbose_name='Объект'),
        ),
        migrations.CreateModel(
            name='ObjectRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rooms', verbose_name='Фото')),
                ('total_area', models.FloatField(verbose_name='Общая площадь')),
                ('block', models.CharField(max_length=50, verbose_name='Блок')),
                ('count', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('entrance', models.PositiveIntegerField(verbose_name='Подъезд')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('status', models.CharField(choices=[('SOLD', 'Sold'), ('NOT_SOLD', 'Not Sold')], default='NOT_SOLD', max_length=50, verbose_name='Статус')),
                ('object_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='apis.object', verbose_name='Объект')),
            ],
        ),
    ]
