# Generated by Django 5.1.1 on 2024-09-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_company_alter_object_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Объект', 'verbose_name_plural': '2. Объекты'},
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Фейсбук'),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='Land House', max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=9980010101, max_length=13, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='company',
            name='you_tube',
            field=models.URLField(blank=True, null=True, verbose_name='Ютуб'),
        ),
    ]
