# Generated by Django 5.1.1 on 2024-09-06 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_object_options_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ф.И.О.')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OLD', 'Old')], default='NEW', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка на общей информации',
                'verbose_name_plural': '4. Заявка на общей информации',
            },
        ),
        migrations.CreateModel(
            name='ApplicationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ф.И.О.')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OLD', 'Old')], default='NEW', max_length=50, verbose_name='Статус')),
                ('object_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Заявка об объекте',
                'verbose_name_plural': '5. Заявка об объекте',
            },
        ),
        migrations.CreateModel(
            name='ApplicationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ф.И.О.')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OLD', 'Old')], default='NEW', max_length=50, verbose_name='Статус')),
                ('room_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.objectroom', verbose_name='Комната объектов')),
            ],
            options={
                'verbose_name': 'Заявка на комнату',
                'verbose_name_plural': '6. Заявка на комнату',
            },
        ),
    ]
