# Generated by Django 5.1.1 on 2024-09-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_new_description_ru_new_description_uz_new_title_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='video',
        ),
        migrations.AddField(
            model_name='new',
            name='photo',
            field=models.ImageField(default='', upload_to='news', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
