# Generated by Django 5.1.1 on 2024-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_remove_new_video_new_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectroom',
            name='block',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=50, verbose_name='Блок'),
        ),
    ]
