# Generated by Django 5.1.1 on 2024-09-18 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_alter_objectroom_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка на общей информации', 'verbose_name_plural': '6. Заявка на общей информации'},
        ),
        migrations.AlterModelOptions(
            name='applicationobject',
            options={'verbose_name': 'Заявка об объекте', 'verbose_name_plural': '7. Заявка об объекте'},
        ),
        migrations.AlterModelOptions(
            name='applicationroom',
            options={'verbose_name': 'Заявка на комнату', 'verbose_name_plural': '8. Заявка на комнату'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новост', 'verbose_name_plural': '9. Новости'},
        ),
        migrations.CreateModel(
            name='ObjectBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=50)),
                ('object_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='apis.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': '4. Блоки',
            },
        ),
        migrations.CreateModel(
            name='ObjectBlockRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rooms', verbose_name='Фото')),
                ('total_area', models.FloatField(verbose_name='Общая площадь')),
                ('block', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=50, verbose_name='Блок')),
                ('count', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('entrance', models.PositiveIntegerField(verbose_name='Подъезд')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('status', models.CharField(choices=[('SOLD', 'Sold'), ('NOT_SOLD', 'Not Sold')], default='NOT_SOLD', max_length=50, verbose_name='Статус')),
                ('block_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='apis.objectblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Комната объектов',
                'verbose_name_plural': '5. Объектные комнаты',
            },
        ),
        migrations.AlterField(
            model_name='applicationroom',
            name='room_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.objectblockroom', verbose_name='Комната объектов'),
        ),
        migrations.DeleteModel(
            name='ObjectRoom',
        ),
    ]
