# Generated by Django 5.1.1 on 2024-09-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_alter_application_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectblockroom',
            name='block',
        ),
    ]
