# Generated by Django 5.2 on 2025-04-20 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_remove_objectblockroom_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('obj1', models.CharField(max_length=300, verbose_name='1 название')),
                ('obj1_uz', models.CharField(max_length=300, null=True, verbose_name='1 название')),
                ('obj1_ru', models.CharField(max_length=300, null=True, verbose_name='1 название')),
                ('key1', models.CharField(max_length=300, verbose_name='Количество 1')),
                ('key1_uz', models.CharField(max_length=300, null=True, verbose_name='Количество 1')),
                ('key1_ru', models.CharField(max_length=300, null=True, verbose_name='Количество 1')),
                ('obj2', models.CharField(max_length=300, verbose_name='2 название')),
                ('obj2_uz', models.CharField(max_length=300, null=True, verbose_name='2 название')),
                ('obj2_ru', models.CharField(max_length=300, null=True, verbose_name='2 название')),
                ('key2', models.CharField(max_length=300, verbose_name='Количество 2')),
                ('key2_uz', models.CharField(max_length=300, null=True, verbose_name='Количество 2')),
                ('key2_ru', models.CharField(max_length=300, null=True, verbose_name='Количество 2')),
                ('obj3', models.CharField(max_length=300, verbose_name='3 название')),
                ('obj3_uz', models.CharField(max_length=300, null=True, verbose_name='3 название')),
                ('obj3_ru', models.CharField(max_length=300, null=True, verbose_name='3 название')),
                ('key3', models.CharField(max_length=300, verbose_name='Количество 3')),
                ('key3_uz', models.CharField(max_length=300, null=True, verbose_name='Количество 3')),
                ('key3_ru', models.CharField(max_length=300, null=True, verbose_name='Количество 3')),
            ],
            options={
                'verbose_name': 'О Компании',
                'verbose_name_plural': '9. О Компании',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, null=True, verbose_name='веб-адрес')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='ютуб-адрес')),
                ('image', models.ImageField(upload_to='banners/')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': '8. Баннер',
            },
        ),
        migrations.CreateModel(
            name='AboutCompanyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apis.aboutcompany')),
            ],
        ),
    ]
